version: "3.8"
services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - "${SERVICE_PORT:-3080}:${SERVICE_PORT:-3080}"
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - PORT=${SERVICE_PORT:-3080}
      - FQDN=${SERVICE_FQDN}
      - NODE_ENV=production
      - DOMAIN_CLIENT=http://${SERVICE_FQDN}:${SERVICE_PORT:-3080}
      - DOMAIN_SERVER=http://${SERVICE_FQDN}:${SERVICE_PORT:-3080}
      - ALLOW_REGISTRATION=true
      - ALLOW_SOCIAL_LOGIN=true
      - ALLOW_EMAIL_LOGIN=true
      - ALLOW_PASSWORD_RESET=true
      - ALLOW_SOCIAL_REGISTRATION=true
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - SESSION_EXPIRY=1000 * 60 * 15
      - REFRESH_TOKEN_EXPIRY=(1000 * 60 * 60 * 24) * 7
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${SERVICE_CREDS_KEY}
      - CREDS_IV=${SERVICE_CREDS_IV}
      - OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - NO_INDEX=true
      - DEBUG_LOGGING=true
      - APP_TITLE=${SERVICE_APP_TITLE:-Practical DevSecOps}
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=true
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs

  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    environment:
      - SEARCH=true
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.7:/meili_data

  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - RAG_PORT=${RAG_PORT:-8000}
      - OPENAI_API_KEY=${SERVICE_OPENAI_API_KEY}
    restart: always
    depends_on:
      - vectordb

volumes:
  pgdata2:
